# Generated by Django 5.2.8 on 2025-12-12 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antenne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('lieux', models.CharField(blank=True, max_length=150, null=True)),
                ('gerant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Antenne',
                'verbose_name_plural': 'Antennes',
            },
        ),
    ]
