# Generated by Django 5.2.8 on 2025-11-29 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalstep',
            old_name='validated_at',
            new_name='approved_at',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='validationthreshold',
            name='approver',
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='role',
            field=models.CharField(choices=[('gerant', "Gérant d'antenne"), ('admin', 'Admin central'), ('directeur', 'Directeur'), ('superviseur', 'Superviseur régional')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validationthreshold',
            name='role',
            field=models.CharField(choices=[('gerant', "Gérant d'antenne"), ('admin', 'Admin central'), ('directeur', 'Directeur'), ('superviseur', 'Superviseur régional')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='expense.expense'),
        ),
        migrations.AlterField(
            model_name='validationthreshold',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
