# Generated by Django 5.2.8 on 2025-11-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_validated_at_approvalstep_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmoney',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='validationthreshold',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
