# Generated by Django 5.2.8 on 2025-11-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_load_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
