# Generated by Django 5.2.8 on 2025-12-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_antenne'),
        ('sales', '0005_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Impayé'), ('Paid', 'Payé')], default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductByAntenne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('antenne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.antenne')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
            ],
        ),
    ]
