# Generated by Django 5.2.8 on 2025-12-12 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_credit_productbyantenne'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
    ]
