# Generated by Django 5.2.8 on 2025-12-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_credit_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale'),
        ),
    ]
